### ISSUE TITLE
Ares missing shaders

### ISSUE THREAD

**Issue by aboutafter** [flathub/dev.ares.ares#18]
The Flatpak version of Ares is missing the shaders for me. 

I can only select between "None" and "Blur". In Vulkan and OpenGL. 

![image](https://user-images.githubusercontent.com/11254299/179209451-e304381d-0cbc-4b32-9882-ebd69509a258.png)

**Comment by ghisvail** [comment]
Which entries are missing? I am afraid I can't do much with what you reported.

**Comment by aboutafter** [comment]
I've downloaded the windows version and these are the contents of the shaders folder:
![image](https://user-images.githubusercontent.com/11254299/179349205-beda8da6-5baa-4396-a8f1-2b9916542484.png)

**Comment by ghisvail** [comment]
Looking at the build log of the latest version I see this:

```txt
cp -R ../ares/Shaders/* /app/share/ares/Shaders/
```

So they should all be present. Please wait for the next update and report if there is still stuff missing.

**Comment by aboutafter** [comment]
v129 has the same problem.

**Comment by aboutafter** [comment]
FYI, I can use the shaders if I copy them to /home/.var/app/dev.ares.ares/data/ares/Shaders

**Comment by ghisvail** [comment]
The shaders are correctly installed where they should be but they are not picked up by `ares` at launch.

Perhaps @LukeUsher could help us figure out how to fix this? Looks like `ares` does not find shaders when it's installed with a custom prefix?

**Comment by ghisvail** [comment]
Unless the solution is using a wrapper script that copies the content of `$prefix/share/data/Shaders/*` to the users data directory before launch.

**Comment by Sunspark-007** [comment]
No shaders as of 130.1 on the Steam Deck with the Ares flatpak.

This issue also affects other flatpaks with a similar structure such as bsnes.

**Comment by ghisvail** [comment]
Will be fixed with the next update to v134 ⏳
