### ISSUE TITLE
Unable to save games: `The current save path is read only`

### ISSUE THREAD

**Issue by brandonbeaumia** [flathub/dev.ares.ares#19]
In the Flatpak distribution of Ares, I can't save my games due to a persistent `The current save path is read only` error. The filesystem permission via `flatpak info --show-permissions dev.ares.ares` is listed as `home:ro` (read only) instead of just `home`. Should it be `home` instead so we have write access or is there something else I'm missing?

**Comment by ghisvail** [comment]
What do you mean by "saving games"?

**Comment by brandonbeaumia** [comment]
Saving the game to the virtual "memory card" or saving the state, neither work.

![Screenshot from 2022-08-20 11-23-28](https://user-images.githubusercontent.com/650565/185757133-d8b27c3b-6dfc-46ef-9b5b-ddaa735196cf.png)

If I ignore this error and play, attempting to save via in-game menus results in the error I listed initially. Attempting to save the state results in a more vague "Failed to save state to slot 1".  If I go into Settings the path is set to "Same as game path", which per the Flatpak permissions is not writable. I also can not change it to a location that _is_ writable, because the file picker that comes up does not show hidden files for me to navigate to the Flatpak's location. Nor would I really want to save my games within the Flatpak's sandbox, for a multitude of reasons.

**Comment by ghisvail** [comment]
Ok that's for save states then. What's the default save location proposed by `ares`?

**Comment by brandonbeaumia** [comment]
"Same as game path" is the default location for saves. If playing games off of an external drive, even allowing write access to Home wouldn't cover all use cases. I think to ensure no features are lost in the Flatpak version the permission would have to be filesystem=host. I'm sure there's a way to make it work with portals, but this is the quick & dirty fix, anyway.

**Comment by ghisvail** [comment]
This code base of this app is so old that it is unlikely to use portals anytime soon.

Feel free to submit a PR closing this issue with the appropriate permissions.
